### ISSUE TITLE
Error in Node-RED 0.18.2

### ISSUE THREAD

**Issue by natcl** [high-u/node-red-contrib-separate-flow-json#1]
Just tried this in Node-RED 0.18.2 and I get this error:
```
TypeError: Cannot read property 'replace' of undefined
```
I'm running Node-RED locallly (by specifying a local dir using -u)

**Comment by natcl** [comment]
Full error:
```
7 Feb 10:34:54 - [error] [separate-flow-json:51817a74.891a54] TypeError: Cannot read property 'replace' of undefined
    at sepfunctempNode.<anonymous> (/Users/Nat/Desktop/node-red/separate/node_modules/node-red-contrib-separate-flow-json/separate-flow-json.js:12:72)
    at emitOne (events.js:116:13)
    at sepfunctempNode.emit (events.js:211:7)
    at sepfunctempNode.Node.receive (/Users/Nat/Desktop/node-red/separate/node_modules/node-red/red/runtime/nodes/Node.js:215:14)
    at InjectNode.Node.send (/Users/Nat/Desktop/node-red/separate/node_modules/node-red/red/runtime/nodes/Node.js:137:22)
    at InjectNode.<anonymous> (/Users/Nat/Desktop/node-red/separate/node_modules/node-red/nodes/core/core/20-inject.js:77:22)
    at emitOne (events.js:116:13)
    at InjectNode.emit (events.js:211:7)
    at Timeout._onTimeout (/Users/Nat/Desktop/node-red/separate/node_modules/node-red/nodes/core/core/20-inject.js:58:20)
    at ontimeout (timers.js:475:11)
```
